Milestone/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Milestone.Models;
using Milestone.Services;
using Milestone.Utility;
using NLog;

namespace Milestone.Controllers
{
    public class LoginController : Controller
    {
        public static int userId = 0;
        private static Logger logger = LogManager.GetLogger("LoginAppLoggerrule");

        /// <summary>
        /// The function returns a view for the Index page.
        /// </summary>
        /// <returns>
        /// The method is returning a View result.
        /// </returns>
        public IActionResult Index()
        {
            return View();
        }


        /// <summary>
        /// The ProcessLogin function checks if the provided user credentials are valid, logs the user in if they are, and
        /// returns the appropriate view.
        /// </summary>
        /// <param name="UserModel">UserModel is a class that represents a user in the system. It contains properties such
        /// as UserName and Password, which are used to authenticate the user during the login process.</param>
        /// <returns>
        /// The method is returning an IActionResult. The specific view being returned depends on whether the user login is
        /// successful or not. If the login is successful, the method returns the "LoginSuccess" view with the user model as
        /// the parameter. If the login is unsuccessful, the method returns the "LoginFailure" view with the user model as
        /// the parameter.
        /// </returns>
        [LogActionFilter]
        public IActionResult ProcessLogin(UserModel user)
        {
            UserDAO userDAO = new UserDAO();

            if (userDAO.FindUserByNameAndPasswordValid(user))
            {
                //remember user logged in
                HttpContext.Session.SetString("username", user.UserName);

                userId = userDAO.FindUserIdByNameAndPassword(user);
                MyLogger.GetInstance().Info("Login Success");
                return View("LoginSuccess", user);
            }
            else
            {
                //remove if unsuccessful
                HttpContext.Session.Remove("username");

                MyLogger.GetInstance().Info("Login Failure");
                return View("LoginFailure", user);
            }
        }
    }
}

Milestone/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Milestone.Models;
using Milestone.Services;

namespace Milestone.Controllers
{
    public class RegisterController : Controller
    {
        /// <summary>
        /// The function returns a view for the Index page.
        /// </summary>
        /// <returns>
        /// The method is returning a View result.
        /// </returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// The function processes the registration of a user and returns a view based on whether the registration is
        /// successful or not.
        /// </summary>
        /// <param name="UserModel">The UserModel is a class that represents the data structure of a user. It typically
        /// contains properties such as username, password, email, and other relevant information about the user.</param>
        /// <returns>
        /// The method is returning a IActionResult.
        /// </returns>
        public IActionResult ProcessRegister(UserModel user)
        {
            UserDAO securityDAO = new UserDAO();

            if (securityDAO.RegisterUserValid(user))
            {
                return View("RegisterSuccess", user);
            }
            else
            {
                return View("RegisterFailure", user);
            }
        }
    }
}

Milestone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Milestone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href='https://fonts.googleapis.com/css?family=Bungee' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/paperkit.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Milestone.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       <partial name="_navbar"/>
    </header>
    <div class="" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted" style="background-color:black;padding-top:1.1em;">
        <div class="container">
            &copy; 2023 - Milestone - <a asp-area="" asp-controller="Home" style="color:white"asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/paperkit.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Milestone/Views/Shared/_navbar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Milestone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="/">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index">Login</a>

        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Register" asp-action="Index">Register</a>

        </li>
     <!--   <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Minesweeper" asp-action="Index">Skip Login</a>
                   </li> -->
      </ul>
    </div>
  </div>
</nav>